-- MySQL Script generated by MySQL Workbench
-- Wed Mar  8 10:56:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instituicao` (
  `idInstituicao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NULL,
  PRIMARY KEY (`idInstituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `Instituicao_idInstituicao` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_Curso_Instituicao1_idx` (`Instituicao_idInstituicao` ASC) VISIBLE,
  CONSTRAINT `fk_Curso_Instituicao1`
    FOREIGN KEY (`Instituicao_idInstituicao`)
    REFERENCES `mydb`.`Instituicao` (`idInstituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Curso` (
  `Usuario_idUsuario` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Curso_idCurso`),
  INDEX `fk_Usuario_has_Curso_Curso1_idx` (`Curso_idCurso` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Curso_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Curso_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Curso_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `mydb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Edital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Edital` (
  `idEdital` INT NOT NULL AUTO_INCREMENT,
  `semestre` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEdital`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario_aluno` INT NOT NULL,
  `Usuario_idUsuario_responsavel` INT NOT NULL,
  `Edital_idEdital` INT NOT NULL,
  PRIMARY KEY (`idProjeto`),
  INDEX `fk_Projeto_Usuario1_idx` (`Usuario_idUsuario_aluno` ASC) VISIBLE,
  INDEX `fk_Projeto_Usuario2_idx` (`Usuario_idUsuario_responsavel` ASC) VISIBLE,
  INDEX `fk_Projeto_Edital1_idx` (`Edital_idEdital` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario_aluno`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_Usuario2`
    FOREIGN KEY (`Usuario_idUsuario_responsavel`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_Edital1`
    FOREIGN KEY (`Edital_idEdital`)
    REFERENCES `mydb`.`Edital` (`idEdital`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projeto_has_Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projeto_has_Colaborador` (
  `Projeto_idProjeto` INT NOT NULL,
  `Usuario_idUsuario_colaborador` INT NOT NULL,
  PRIMARY KEY (`Projeto_idProjeto`, `Usuario_idUsuario_colaborador`),
  INDEX `fk_Projeto_has_Usuario_Usuario1_idx` (`Usuario_idUsuario_colaborador` ASC) VISIBLE,
  INDEX `fk_Projeto_has_Usuario_Projeto1_idx` (`Projeto_idProjeto` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_has_Usuario_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `mydb`.`Projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario_colaborador`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario_avaliadorResponsavel` INT NOT NULL,
  `Usuario_idUsuario_avaliadorSuplente` INT NULL,
  `Projeto_idProjeto` INT NOT NULL,
  `parecerAvaliadorResponsavel` LONGTEXT NOT NULL,
  `parecerAvaliadorSuplente` LONGTEXT NULL,
  `notaAvaliadorResponsavel` INT NOT NULL,
  `notaAvaliadorSuplente` INT NULL,
  `parecerComissao` LONGTEXT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `fk_Avaliacao_Usuario1_idx` (`Usuario_idUsuario_avaliadorResponsavel` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Usuario2_idx` (`Usuario_idUsuario_avaliadorSuplente` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Projeto1_idx` (`Projeto_idProjeto` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliacao_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario_avaliadorResponsavel`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Usuario2`
    FOREIGN KEY (`Usuario_idUsuario_avaliadorSuplente`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `mydb`.`Projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
